### ISSUE TITLE
"Operation not permitted" error on WSL.

### ISSUE THREAD

**Issue by baajayi** [run-llama/create-llama#117]
![image](https://github.com/run-llama/create-llama/assets/81062134/37705091-216d-473b-bd09-7729b657dacf)
It advised that this should be reported as a bug.
I'm using Ubuntu on WSL and I'm getting this "operation not permitted" error. It looks like it was going to make a directory on the Windows System.

**Comment by rmandrad** [comment]
i get a different error on wsl ubuntu 24.04 - OS not supported

` npx create-llama@latest
✔ What is your project named? … test
✔ Which template would you like to use? › Chat
✔ Which framework would you like to use? › NextJS
✔ Would you like to set up observability? › No
✔ Please provide your OpenAI API key (leave blank to skip): …
✔ Which data source would you like to use? › Use local folders
Unsupported OS error!`

**Comment by marcusschiesser** [comment]
@baajayi seems like you don't have access to the `c:\\windows\test_llama` folder - @rmandrad your issue is covered in #47
