### ISSUE TITLE
Listing Ollama models failed. Is 'ollama' running? TypeError: fetch failed

### ISSUE THREAD

**Issue by crown-king** [run-llama/create-llama#126]
Ollama models throw TypeError in CLI.

(polenv) PS C:\UniCult\full-stack build check> npx create-llama@latest --ask-models
√ What is your project named? ... my-app
√ Which template would you like to use? » Chat
√ Which framework would you like to use? » NextJS
√ Would you like to set up observability? » No
√ Which model provider would you like to use » Ollama
√ Which LLM model would you like to use? » llama3:8b
Listing Ollama models failed. Is 'ollama' running? TypeError: fetch failed
(polenv) PS C:\UniCult\full-stack build check>

**Comment by marcusschiesser** [comment]
@crown-king on which URL is 'ollama' running?

**Comment by marcusschiesser** [comment]
Closing this - Please reopen @crown-king if this is still an issue
