### ISSUE TITLE
3 high severity vulnerabilities

### ISSUE THREAD

**Issue by yasir23** [run-llama/create-llama#171]
npm i llamaindex@latest
npm WARN deprecated @aws-sdk/protocol-http@3.374.0: This package has moved to @smithy/protocol-http
npm WARN deprecated @aws-sdk/signature-v4@3.374.0: This package has moved to @smithy/signature-v4

added 126 packages, changed 7 packages, and audited 1238 packages in 53s

3 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

**Comment by marcusschiesser** [comment]
Fixed in create-llama@0.1.22
