### ISSUE TITLE
Azure Open Ai Model Provider Issue

### ISSUE THREAD

**Issue by vaibhavkumbhar4** [run-llama/create-llama#178]
When using the Azure Open AI Model Provider option, I encountered a 404-Resource Not Found error. It seems additional configurations, such as 'azure_endpoint' and 'api_version', might need to be added to settings.py.

**Comment by marcusschiesser** [comment]
Azure OpenAI support has not yet been added officially, meanwhile, please try to set the following env variables:
`AZURE_OPENAI_ENDPOINT` and `OPENAI_API_VERSION`

**Comment by marcusschiesser** [comment]
Thanks. Fixed in Release 0.1.25
