### ISSUE TITLE
Question suggestions do not use N_QUESTION_TO_GENERATE variable

### ISSUE THREAD

**Issue by Arputikos** [run-llama/create-llama#190]
When using python backend, generated project contains bug such as in suggestion.py
N_QUESTION_TO_GENERATE variable is not used at all to generate NEXT_QUESTIONS_SUGGESTION_PROMPT
Even when it's set to 3 by default it's generating 5 questions (and in the logs we can see that text sent to the LLM provider 
contains "...me $number_of_questions questions..." instead of the variable itself.

How to reproduce:
create project with python backend and next.js frontend, see that there are 5 question suggestions

**Comment by marcusschiesser** [comment]
Thanks. Fixed in Release 0.1.26
