### ISSUE TITLE
Incorrect References in settings.ts not caught by e2e

### ISSUE THREAD

**Issue by balasubramaniam-ramasamy** [run-llama/create-llama#212]
I generated the app with the combinations of NextJs +  Express + MongoDB.

The below code is found in **".\backend\src\controllers\engine\generate.ts"** and **".\backend\src\controllers\engine\index.ts"**:-

`import { MongoDBAtlasVectorSearch } from "llamaindex/storage/vectorStore/MongoDBAtlasVectorSearch";`

However, I had to resolve the reference error with below code:

`import { MongoDBAtlasVectorSearch } from "llamaindex";`

Please, check if this update is needed.

**Comment by balasubramaniam-ramasamy** [comment]
Also in `settings.ts`
```
import { HuggingFaceEmbedding } from "llamaindex/embeddings/HuggingFaceEmbedding";
import { OllamaEmbedding } from "llamaindex/embeddings/OllamaEmbedding";
import { ALL_AVAILABLE_ANTHROPIC_MODELS } from "llamaindex/llm/anthropic";
import { Ollama } from "llamaindex/llm/ollama";
```

**Comment by marcusschiesser** [comment]
Thanks @balasubramaniam-ramasamy we'll update the references

**Comment by marcusschiesser** [comment]
@thucpn i updated the MongoDB references. Please have a look why the `settings.ts` are not caught by our e2e
