### ISSUE TITLE
Swagger support - swagger works in FastAPI but Not in Express

### ISSUE THREAD

**Issue by balasubramaniam-ramasamy** [run-llama/create-llama#220]
Hi

I tried to create different backends. 
**WORKS**: In **FastAPI** backend, the apis are exposed in swagger in the url - http://0.0.0.0:8000/docs

NEED **HELP**: However, when I run `express \ nodejs` in localhost, it is not showing swagger.
I tried this below url -- http://localhost:8000/api/<name-in-backend-pacakage.json>/api/swagger/

Also, I am not finding swagger.json, in express backend project, which is supposed contain the APIs exposed by this backened.

Kindly, help to resolve. 
3RD BACKEND: I am not sure how swagger works in next.js (backend/fullstack). Will it support in next.js (backend) too.?

**Comment by marcusschiesser** [comment]
yes, neither express no nextjs do support swagger out of the box

**Comment by balasubramaniam-ramasamy** [comment]
If we can implement Swagger, it will be good, as it is available.

https://www.npmjs.com/package/swagger-ui-express
https://www.npmjs.com/package/next-swagger-doc

Thanks

**Comment by marcusschiesser** [comment]
@balasubramaniam-ramasamy not on the roadmap on the moment, but you're welcome to send a PR
