### ISSUE TITLE
Generation crashing in docker

### ISSUE THREAD

**Issue by leonardpauli** [run-llama/create-llama#231]
As per the readme:

```
docker run \
  --rm \
  -v $(pwd)/.env:/app/.env \
  -v $(pwd)/config:/app/config \
  -v $(pwd)/data:/app/data \
  -v $(pwd)/storage:/app/storage \
  hacknight \
  poetry run generate
```

crashed after a while at `SimpleDocumentStore.from_persist_dir(STORAGE_DIR)` in backend/app/engine/generate.py

removing the `-v $(pwd)/storage:/app/storage` made it work (but obviously not persisting)

(not reproducing now, but posting issue on request from the event!)

**Comment by marcusschiesser** [comment]
@leonardpauli, did it work in the end? This kind of error might be related to Docker being unable to mount the volume due to file system restrictions
