### ISSUE TITLE
backend: config/loaders.yaml

### ISSUE THREAD

**Issue by lambdaofgod** [run-llama/create-llama#270]
When I run `poetry run generate` I get

```FileNotFoundError: [Errno 2] No such file or directory: 'config/loaders.yaml'```

Where can I find information on this file?

**Comment by marcusschiesser** [comment]
`config/loaders.yaml` is usually generated by create-llama - what configuration did you use?

**Comment by lambdaofgod** [comment]
I created the project without any example data.

**Comment by leehuwuj** [comment]
the `loader.yml` config file is generated dynamically depending on the data source you pick. If you select no data source then you don't need to run `poetry run generate`
