### ISSUE TITLE
Cannot find module '.../node_modules/llamaindex/dist/cjs/storage/vectorStore/PGVectorStore.js'

### ISSUE THREAD

**Issue by akma-iman** [run-llama/create-llama#310]
After performing 'npm run generate', I got an error where the project unable to find module for PGVectorStore. The error highlight at this line : **_import { PGVectorStore } from "llamaindex/storage/vectorStore/PGVectorStore";_** in generate.ts file. I hoping this issue can be solved.

I am using latest create-llama version 0.2.8 and PostgresSQL as vector database. I am attach snapshot of my setup here.

Update : I manage to solve this issue by removing this line, **_import { PGVectorStore } from "llamaindex/storage/vectorStore/PGVectorStore";_** in generate.ts file and call the 'PGVectorStore' class directly from llamaindex library. Even though it is solved now, I getting different error which is this : [ERR_MODULE_NOT_FOUND]: Cannot find package 'pg' imported from '.../node_modules/llamaindex/dist/cjs/vector-store/PGVectorStore.js'

![Screenshot 2024-09-23 at 2 57 50 PM](https://github.com/user-attachments/assets/db1b62cf-4ce5-4a0e-b8ae-a3b9e1379395)

**Comment by akma-iman** [comment]
Hi @marcusschiesser! Yes I have adding 'pg' and 'pgvector' to package.json file. The issue is gone now but I faced other issue which is this : error: expected 1536 dimensions, not 1024. I simply change EMBEDDING_DIM in env file from 1024 to 1536. And now I successfully created embeddings. 

But once I run localhost and try to type text in the chat box, I got this error : **_TypeError: llamaindex__WEBPACK_IMPORTED_MODULE_0__.PGVectorStore is not a constructor.** I am not sure how to fix this. 
![Screenshot 2024-09-24 at 10 46 42 AM](https://github.com/user-attachments/assets/a25670c1-c32f-4157-9791-03f6aaf09653)

**Comment by marcusschiesser** [comment]
Sorry for the trouble. The imports and the package.jsons are now updated in create-llama 0.2.9. Please try again.

**Comment by akma-iman** [comment]
Hi @marcusschiesser and @thucpn. Thank you for the update. I have try create-llama 0.2.9 from scratch and I am still stuck with this [same](https://github.com/run-llama/create-llama/issues/310#issuecomment-2370005083) error : **_TypeError: llamaindex__WEBPACK_IMPORTED_MODULE_0_.PGVectorStore is not a constructor**. This error appear after I try to submit my text in the chat box. May I know if this error is fixable?

**Comment by marcusschiesser** [comment]
fixed in release 0.2.11

**Comment by akma-iman** [comment]
Thank you very much! There are no error now and It is working as expected. I really appreciate you guys hard work. Oh by the way, I am not sure why the model does not read my vector store and just provide unrelated response. I think I facing the same issue like here #326
