### ISSUE TITLE
Pinecone Module Not Found in Fresh Create-Llama Setup for DuckDuckGo Search RAG

### ISSUE THREAD

**Issue by klei30** [run-llama/create-llama#314]
Hi,

I'm encountering an issue with a fresh create-llama project using the Agentic RAG (DuckDuckGo Search) template. After setting it up and performing the first query, I receive an error indicating that the Pinecone module cannot be resolved.

Steps to Reproduce:

Run npx create-llama@latest.
Choose the following options:
Template: Agentic RAG (e.g., chat with docs)
Framework: NextJS
OpenAI API key: Skip
Data source: Example PDF
Add another data source: No
Use LlamaParse for RAG: No
LlamaCloud API key: Skip
Vector database: Pinecone
Tools: DuckDuckGo search, Wikipedia, Weather, Code Interpreter, etc.
Run the project and execute a query.
Error is thrown.
![image](https://github.com/user-attachments/assets/a12bde9d-723a-438e-910e-5f5e4ee208bb)

![image](https://github.com/user-attachments/assets/424e951c-adf2-475f-98fb-230cbf9853ef)

**Comment by robotson** [comment]
can you try importing like
 
```
import { PineconeVectorStore } from "llamaindex";
```

I've noticed the create-llama installer currently seem to be a little out of date with regard to where some packages are actually exported from

**Comment by marcusschiesser** [comment]
Sorry for the trouble. The imports and the package.jsons are now updated in create-llama 0.2.9. Please try again.

**Comment by marcusschiesser** [comment]
fixed in release 0.2.11
