### ISSUE TITLE
Issues with Resource Retrieval and Response Length in LlamaIndex 0.2.9

### ISSUE THREAD

**Issue by klei30** [run-llama/create-llama#318]
I have been working with LlamaIndex to create a Retrieval-Augmented Generation (RAG) setup using DuckDuckGo search. However, I encountered a couple of issues after upgrading to version 0.2.9.

Issues:

Resource Retrieval in UI:

After upgrading to version 0.2.9, I am unable to see the resources retrieved in the UI. This is concerning as I rely on the displayed resources for context in my queries.
Response Length:

I modified the max_tokens parameter to increase the length of the responses. However, I am still receiving only a small paragraph as a response, which does not meet my expectations for more detailed output.
Import Change:

I updated my import statement to:
javascript
Copy code
import { LlamaParseReader } from "llamaindex";
Despite this change, I still do not see any resources in the UI when I ask questions.
Questions:

Is there any workaround for displaying the resources in the UI?
Are there known issues related to max_tokens not functioning as expected in the latest release?
Environment:

LlamaIndex Version: 0.2.9
Setup: RAG with DuckDuckGo search

I would really appreciate if you can just suggest for the moment a stable version that works well rag agent + DuckDuckGo. 

![image](https://github.com/user-attachments/assets/f8f9b8e1-c28c-48f8-99fc-735f136d1db3)

![image](https://github.com/user-attachments/assets/4ec8488b-a620-47a9-b00a-f8a92abc41c8)

**Comment by marcusschiesser** [comment]
can you try release 0.2.11 please?
