### ISSUE TITLE
Node Sources Missing in UI and RAG Pipeline Unable to Read Vector Database in Release 0.2.11

### ISSUE THREAD

**Issue by klei30** [run-llama/create-llama#326]
Release 0.2.11 (#325)
Description: Hi, I have tried the new version (Release 0.2.11), and I am still facing the same issues, particularly with the node sources in the UI. They do not appear as expected.

Steps to Reproduce:

Configure top_k=3.
Change the system prompt to be more in tune.
Attempt to run the RAG pipeline.
Observed Behavior: The RAG pipeline seems to be broken, as shown in the image. It cannot read the vector database, and the node sources in the UI fail to appear.

Screenshot:

![image](https://github.com/user-attachments/assets/65caa837-b6b9-40ea-8998-d3638f94b729)

Expected Behavior: The UI should show the correct node sources, and the RAG pipeline should read the vector database without issues like in this example

![image](https://github.com/user-attachments/assets/ed7b22ab-13f2-46e6-a4e1-ce97740ada59)

Environment:

Version: 0.2.11
Configuration: topk=3, modified system prompt

I am also using Node v20.17.0 maybe i need an older node version ?

**Comment by marcusschiesser** [comment]
@klei30 which backend are you using (nextjs, python, express) and which vector db?

**Comment by marcusschiesser** [comment]
@klei30 seems like the `queryFilter.ts` is not working with pinecone and queryenginetool - we'll have a look at this next week - meanwhile, you can try another vector DB

**Comment by marcusschiesser** [comment]
@klei30 currently, with typescript only milvus and no vector store is working, we're adding the metadata filters now one by one to the framework. Once this PR is released: https://github.com/run-llama/LlamaIndexTS/pull/1272, it will work with Pinecone

**Comment by marcusschiesser** [comment]
Qdrant and Pinecone both work now again with release 0.2.17

**Comment by marcusschiesser** [comment]
Ah sorry, it seems i misunderstood your problem. 
1. The top_k defines the maximum of nodes that are retrieved from the vector db (nodes are subsets of documents)
2. After retrieval irrelevant nodes are filtered (see `NODE_SCORE_THRESHOLD` in the source)
