### ISSUE TITLE
I had this issue as well when i deployed on vercel. I had to update my Next config file to automatically trace the dependency for all api routes

### ISSUE THREAD

**Issue by mrsamirr** [run-llama/create-llama#334]
I had this issue as well when i deployed on vercel. I had to update my Next config file to automatically trace the dependency for all api routes
model: meta-llama/Meta-Llama-3-8B-Instruct
-add this in you `next.config.js`

` experimental: {
    outputFileTracingIncludes: {
      "/api/**/*": ["./node_modules/**/*.wasm", "./node_modules/tiktoken/**/*.wasm"],
      "/*": ["./cache/**/*"],
    },
    serverComponentsExternalPackages: ["sharp", "onnxruntime-node", "tiktoken"],
  },`
  
  & also in `package.json`
  
  add this scripts: `"build": "next build && cp ./node_modules/tiktoken/tiktoken_bg.wasm .next/server/chunks/"`
  
  if any case checkout [repo](https://github.com/mrsamirr/ask-this-website)
  
before : 
![Screenshot from 2024-10-01 22-16-51](https://github.com/user-attachments/assets/fe688c12-7eee-465f-b177-65a13e5dfda6)

  after:
![image](https://github.com/user-attachments/assets/6ec9875d-4a22-435d-8f2f-4b56b561d8e0)

_Originally posted by @mrsamirr in https://github.com/run-llama/create-llama/issues/164#issuecomment-2387573668_

**Comment by marcusschiesser** [comment]
should not be necessary doing this using `withLlamaIndex` in `next.config.js` 

what's the error that you're getting?

what's the llamaindex version that you're using?
