### ISSUE TITLE
Add support for NextJS RSC

### ISSUE THREAD

**Issue by marcusschiesser** [run-llama/create-llama#345]
We need first to find out what kind of artifact we would like to generate:

1. Start with a create-llama "Agentic RAG" template using NextJS - commit it to a repo
2. convert the generated code to use RSC (take inspirations from https://github.com/vercel/ai-chatbot and https://github.com/run-llama/LlamaIndexTS/tree/master/packages/llamaindex/e2e/examples/nextjs-agent) send a PR to the repo
4. analyze the PR
5. optionally (upgrade to NextJS 15, https://nextjs.org/blog/next-15-rc2)

Goal is to generate a NextJS optimized example first - then we integrate it into the code generator

**Comment by marcusschiesser** [comment]
look into https://github.com/vercel/ai-chatbot

**Comment by himself65** [comment]
To this one, for now @llamaindex/core is supporting nextjs rsc and we are using it in our new document website. 
in the future, we goona decoupling the module into core or a new module. Making sure import llamaindex could work without configuration
