### ISSUE TITLE
DuckDuckGo Search feature seems it not working at all

### ISSUE THREAD

**Issue by KleiAliaj** [run-llama/create-llama#433]
I am using create llama app @latest, and in  every setup, python, nextJS, express,  DuckDuckGo seems to keep loading and not showing any results.

Is there any workaround regarding to fix this because i am trying but no results so far?

Maybe the library is deprecated or something?

Any help will be more than welcomed

Thank you

**Comment by marcusschiesser** [comment]
Duplicate of #427
