### ISSUE TITLE
Dependency problem when using azure openai models

### ISSUE THREAD

**Issue by kris7ian** [run-llama/create-llama#435]
I tried to run `poetry run generate` and got:

```
ImportError: Azure OpenAI support is not installed. Please install it with `poetry add llama-index-llms-azure-openai` and `poetry add llama-index-embeddings-azure-openai`
```

I then ran `poetry add llama-index-llms-azure-openai` as suggested but ran into:

```
Because no versions of llama-index-llms-azure-openai match >0.3.0,<0.4.0
 and llama-index-llms-azure-openai (0.3.0) depends on llama-index-llms-openai (>=0.3.0,<0.4.0), llama-index-llms-azure-openai (>=0.3.0,<0.4.0) requires llama-index-llms-openai (>=0.3.0,<0.4.0).
So, because app depends on both llama-index-llms-openai (^0.2.0) and llama-index-llms-azure-openai (^0.3.0), version solving failed.
```

I'm new to poetry but tried to update the conflicting `llama-index-embeddings-openai` package with `poetry update llama-index-embeddings-openai` but I got:

`No dependencies to install or update`

Any pointers on how to bump up the dependencies?

**Comment by leehuwuj** [comment]
@kris7ian Did you generate the code using the Azure OpenAI provider options? Generally, in the `pyproject.toml`, you only need to specify these packages from `llama-index`.
e.g:
```
llama-index = "^0.11.17"
llama-index-llms-azure-openai = "0.2.0"
llama-index-embeddings-azure-openai = "0.2.4"
```

**Comment by kris7ian** [comment]
I used the `npx create-llama@latest` I don't think there was an azure specific question there. What do you mean by 

> using the Azure OpenAI provider options

?

Thanks

**Comment by leehuwuj** [comment]
@kris7ian you can run `npx create-llama@latest --pro --ask-models`  to select to generate project with different AI providers:
e.g:
```shell
❯ npx create-llama@latest --pro --ask-models
✔ What is your project named? … test-app
✔ Which template would you like to use? › Agentic RAG (e.g. chat with docs)
✔ Which framework would you like to use? › NextJS
✔ Would you like to set up observability? › No
✔ Which model provider would you like to use › AzureOpenAI
✔ Which LLM model would you like to use? › gpt-4-turbo
✔ Which embedding model would you like to use? › text-embedding-3-small
? Would you like to use a vector database? › - Use arrow-keys. Return to submit.
❯   No, just store the data in the file system
    MongoDB
    PostgreSQL
    Pinecone
    Milvus
    Astra
    Qdrant
    ChromaDB
    Weaviate
    LlamaCloud (use Managed Index)
```

**Comment by leehuwuj** [comment]
Because the option to start with the Azure OpenAI provider have no conflict so I’ll close this ticket.
