### ISSUE TITLE
CORS is missing in the newly generated frontends

### ISSUE THREAD

**Issue by KenjiPcx** [run-llama/create-llama#444]
### Issue
CORS seems to be missing when generating the NextJs frontend with a FastAPI backend.

### Reproduction Steps
1. Create an app with the agentic RAG option (create-llama version 0.3.16)
2. Run frontend and backend and  send a message

### Fix
Just need to add CORS back.
Would've created a PR to fix this, but am held up today, so just reporting the issue here for now :)

**Comment by leehuwuj** [comment]
Hi @KenjiPcx, you can now directly access the chat UI using the backend address, like http://localhost:8000, so it should work without any CORS issues!

**Comment by marcusschiesser** [comment]
yes, @KenjiPcx we removed that on purpose, what's your use case for using CORS?

**Comment by KenjiPcx** [comment]
Oh I see I've been accessing the frontend through localhost:3000 and it was throwing errors

**Comment by KenjiPcx** [comment]
Did anything change with logging too? I can only see the logs of the backend starting and restarting but unable to view logs from anywhere else 😔

**Comment by marcusschiesser** [comment]
You need to set the `NEXT_PUBLIC_CHAT_API` env variable in the generated frontend to point to the URL of chat endpoint in your express backend.
