### ISSUE TITLE
Timescale link doesn't exists.

### ISSUE THREAD

**Issue by meera** [run-llama/create-llama#46]
Link doesn't exists. README points to this URL, and the link doesn't exists.

https://docs.timescale.com/use-timescale/latest/services/create-a-service

**Comment by marcusschiesser** [comment]
@meera Thanks for pointing out - does https://docs.timescale.com/getting-started/latest/services#create-your-timescale-account work for you instead?

**Comment by meera** [comment]
Updated URL looks good. 

Can you consider adding instructions on connecting with other Postgres serves? It will help people like me who didn't know about Timescale.

**Comment by marcusschiesser** [comment]
What are your suggestions? Which other services work with create-llama?

**Comment by marcusschiesser** [comment]
Closing this as Timescale is the number one search for a hosted Postgres with pg/vector
