### ISSUE TITLE
Installation error in Ubuntu 22.04.4 LTS

### ISSUE THREAD

**Issue by ahmedDaoudi-u** [run-llama/create-llama#48]
![image](https://github.com/run-llama/create-llama/assets/107957529/85f066e8-321b-42bf-b883-ec895a432f88)

Hello there, after running the first command In Ubuntu:

npx create-llama@latest

I have run into this error that I have specified in the screenshot above , I am adding this error so that if anyone who would come up with the solution or have the same problem as me would be notified. Thanks.

**Comment by brrock** [comment]
I get same error on Debian 13 but I dual boot with windows so it's fine

**Comment by ahmedDaoudi-u** [comment]
I see ,thanks @brrock I will try that out

**Comment by brrock** [comment]
I wasn't on the LTS node version so will try again

**Comment by marcusschiesser** [comment]
yes, a LTS node version is required - we'll have a look at this with #47

**Comment by brrock** [comment]
Note the error with when you pick a file for the local source and then get a unsupported OS error

**Comment by brrock** [comment]
When I tried on windows as I  also dual boot I errored out errored out in when I indexed the file

**Comment by marcusschiesser** [comment]
Linux errors will be tracked in #47
