### ISSUE TITLE
missing `generate` script

### ISSUE THREAD

**Issue by burn2delete** [run-llama/create-llama#50]
The readme has the following:

> Before you can use your data, you need to index it. If you're using the Next.js or Express apps, run:
> 
> npm run generate
> Then re-start your app. Remember you'll need to re-run generate if you add new files to your data folder.
> 
> If you're using the Python backend, you can trigger indexing of your data by calling:
> 
> poetry run generate
> 

This script seems to be missing from the repo.

**Comment by marcusschiesser** [comment]
Thanks for the bug report, @burn2delete. Please paste the configuration steps you selected that led to your error here.

**Comment by marcusschiesser** [comment]
Closing (no testcase)
