### ISSUE TITLE
Supporting Generative UI 

### ISSUE THREAD

**Issue by meera** [run-llama/create-llama#58]
I see that the generated code is using hooks such as useChat

Any plan for moving to Server Actions and Generative UI? 

As mentioned in this documents - 
https://sdk.vercel.ai/docs/concepts/ai-rsc

**Comment by marcusschiesser** [comment]
No plans as RSC does not support Python backends, but we might soon release a community template at https://github.com/run-llama/create_llama_projects using RSC
