### ISSUE TITLE
Update nextjs-llama3 community template to use latest LlamaIndexTS

### ISSUE THREAD

**Issue by jozemario** [run-llama/create-llama#78]
using create-llama@0.1.1

1 week before it was working now i received errors when calling replicate api, no changes to template just adding api keys and running
using     "llamaindex": "0.3.8"
<img width="995" alt="Screenshot 2024-05-08 at 23 32 38" src="https://github.com/run-llama/create-llama/assets/13593111/d0cd59a5-2a85-4123-be8a-0b2ef5529b1c">

using  llamaindex 0.2.10

<img width="1461" alt="Screenshot 2024-05-08 at 23 34 18" src="https://github.com/run-llama/create-llama/assets/13593111/5a70f5f0-a24b-4f81-abac-29a95bfd39a5">

**Comment by jte0711** [comment]
Had same problem with other class `SimpleDirectoryReader`.

```
Attempted import error: 'SimpleDirectoryReader' is not exported from 'llamaindex' (imported as 'SimpleDirectoryReader').
```

Did i do something wrong with the import? I tried these but same results:

1.
```javascript
import { SimpleDirectoryReader } from "llamaindex/readers/SimpleDirectoryReader";
```
2.
```javascript
import { SimpleDocumentStore, VectorStoreIndex ,SimpleDirectoryReader} from "llamaindex";
```

**Comment by marcusschiesser** [comment]
@jte0711 This is happening with llamaindex `0.2.10`?
